### ISSUE TITLE
Create feature for change color, or opacity background, when scroll on in header

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#100]
In the header component create a resource, which can be enabled via JS, to effect the effect of changing the header color or changing the opacity of the header background.

A good way to use via JS would look like this:

```
header.changeByScroll({
  class: 'red',
  height: 200
})
```

Example: https://codepen.io/jhiam/pen/woZaKZ

**Comment by manaswinidas** [comment]
I'm interested

**Comment by galloj** [comment]
@fabiorogeriosj I think, that I have done it, but I don't know how to do example in docs, because header there isn't fixed. Should I just not make example?

**Comment by fabiorogeriosj** [comment]
@galloj in this case just add a example with text, like this:
![image](https://user-images.githubusercontent.com/1442874/47291743-27f93e00-d5db-11e8-9954-3ddee4125d67.png)
