### ISSUE TITLE
flickering when vertical scrolling

### ISSUE THREAD

**Issue by ngramm** [MobileUI/components#109]
Hi,

I have built the first example provided in mobileUIjs component section here: https://mobileui.github.io/#mobileuijs in an Android device, and when the screen is full, vertical scrolling is enabled automatically, but there is a very annoying flickering effect during scrolling (the header section seems to be moving a bit up and down). Is there any way to avoid this? When I added a  menu in my own application, this looks really bad!

Thanks in advance!

**Comment by fabiorogeriosj** [comment]
Hi @ngramm, show your code here please!

**Comment by ngramm** [comment]
Find the html below-as I said, it's just the official example code for mobileUIjs but I also run mobileui install template cordova-blank and mobileui install header (following the "getting started" guidelines): 
http://195.251.117.126/index.html

**Comment by fabiorogeriosj** [comment]
Your code is not ok, you need add content component in your code, see:

```

<body>

   <div class="header red">
        <h1>Example MobileUI.js</h1>
   </div>

   <div class="content has-header grey-200">
       <div class="list white" id="formCadaster">
          .....
       </div>
   </div>
</body>
```

**Comment by ngramm** [comment]
Yes, it worked!
Many-many thanks!
