### ISSUE TITLE
Closing an alert in 'onclick' event

### ISSUE THREAD

**Issue by digi-chris** [MobileUI/components#110]
I'm trying to use a modal alert to notify the user that they need to log in to complete a function. I thought that MobileUI's alert should work quite well for this, however looking at the documentation, I couldn't see how to call up a function when clicking on a button within the alert. Looking through the code, I figured I probably needed to do something like this:

```
alert({
    title: 'Login Required',
    message: 'You must login in order to complete this task.',
    template: 'login-alert',
    width: '90%',
    buttons: [
        {
            label: 'OK',
            onclick: () => {
                console.log('OK Pressed');
                // fire my login logic here
            }
        },
        {
            label: 'Cancel',
            onclick: () => {
                console.log('Cancel Pressed');
                // go back to the previous screen
            }
        }
    ]
});
```

The issue is, once using the 'onclick' events like this, I can't see how to close the alert down. I can see there's a 'closeAlert' function, however this takes an alert ID, and that value doesn't seem to be exposed outside of the alert itself.

In the end I modified the alert code so that it returns `configAlert.id` after setting up the alert. This meant I could alter the above code as follows:

```
var alertId = alert({
    title: 'Login Required',
    message: 'You must login in order to complete this task.',
    template: 'login-alert',
    width: '90%',
    buttons: [
        {
            label: 'OK',
            onclick: () => {
                console.log('OK Pressed');
                // fire my login logic here
                closeAlert(alertId); // <-- now we can close the alert
            }
        },
        {
            label: 'Cancel',
            onclick: () => {
                console.log('Cancel Pressed');
                // go back to the previous screen
                closeAlert(alertId);
            }
        }
    ]
});
```

This works perfectly well. I would figure a better approach would be to return the alert object, which has a 'close' function, and perform the same trick in there. Or, bind the 'onclick' to the alert object so you can call `this.close()` (or something similar).

Anyway, having said all that, have I missed something obvious that already exists in the code? Is there a way of doing this without modifying anything?

Thanks,

Chris.

**Comment by fabiorogeriosj** [comment]
Hi Chris, I need improve the documentation about alert, sorry, but you need just add `id` atribute in your custom alert, and send this in `closeAlert()`:

```
alert({
    title: 'Login Required',
    id: 'myCustomAlert',
    message: 'You must login in order to complete this task.',
    template: 'login-alert',
    width: '90%',
    buttons: [
        {
            label: 'OK',
            onclick: () => {
                console.log('OK Pressed');
                // fire my login logic here
            }
        },
        {
            label: 'Cancel',
            onclick: () => {
                console.log('Cancel Pressed');
                closeAlert('myCustomAlert');
            }
        }
    ]
});
```

It work for you?

**Comment by digi-chris** [comment]
Brilliant - that worked perfectly, thanks! Sorry I didn't see that in the code.
