### ISSUE TITLE
why My tab  is showing like this

### ISSUE THREAD

**Issue by issevpar** [MobileUI/components#118]
When i add footer tab the list elements going down like this. How can i fix  bottom my tab. Please anyone can help.
![5e5d0b83-4842-4ec9-9b0f-12daae23fd8c](https://user-images.githubusercontent.com/85240/60882085-cf90cc00-a24f-11e9-805a-66018183b55b.jpeg)

**Comment by fabiorogeriosj** [comment]
Hi @issevpar, you can post your HTML code here?

**Comment by issevpar** [comment]
[main.txt](https://github.com/MobileUI/components/files/3377181/main.txt)

I cannot upload .html file .But i upload .txt file. Thanks for your help.

**Comment by fabiorogeriosj** [comment]
I tested your code, you need remove `page` of div content:

`<div class="no-padding grey-100 align-left content">`

And remove has-header the `<body>` element.
