### ISSUE TITLE
iPhone xs/11 notch support

### ISSUE THREAD

**Issue by ang3lx** [MobileUI/components#127]
Hello
I've submitted app on store developed with mobileui, but there is a problem with iPhone with notch and app was rejected
There is a whitebar on top 
How can fix this ui issue ?

**Comment by jhurliman** [comment]
Here's what I did to fix it. The specifics depend on your app layout (whether you have a header, what you want the top of the screen to look like, whether you have buttons on the bottom of the screen, etc).

```
<meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, viewport-fit=cover" />
```

```
.app {
  padding-top: env(safe-area-inset-top);
}

#header {
  top: env(safe-area-inset-top);
}
```
