### ISSUE TITLE
MobileUI Page Not Working on iOS

### ISSUE THREAD

**Issue by Jack-Drake** [MobileUI/components#139]
I am having trouble figuring out why the openPage() function is not working I have tried to compile other code different from mine such as the example given on the mobileui website for page but I have not gotten it to work. When the button is clicked nothing happens there are no errors yet it doesnt work. I have tried to get it to work on android and it works successfully. Any insight as to why it would not work as the website clearly states that it should be working properly.

**Comment by aurorainternet** [comment]
Try to reinstall the cordova inapp browser plugin
This helped me with the same issue while working on legacy project.

**Comment by Jack-Drake** [comment]
Ill try that out rn. Thank you

**Comment by tidelganesh** [comment]
I am also facing same problem.
By default cordova inapp browser plugin not added in my Cordova project.
So Tried installing  cordova inapp browser plugin.
It didn't work. Any thing i missed out?
Please help. Thank you

**Comment by adlylee** [comment]
does anyone know how to fix this ?

**Comment by fabiotindin** [comment]
@adlylee do you have error debug?

Try add ./ in file name, example: `<button class="green" onclick="openPage('./contacts')">Go to a new Page</button>`
