### ISSUE TITLE
Full Screen?

### ISSUE THREAD

**Issue by chrisspen** [MobileUI/components#143]
Is there any built-in support for making the UI go [full-screen](https://developers.google.com/web/fundamentals/native-hardware/fullscreen), so it looks more like a native app?

This library renders some good widgets, but at least in Android, with the notification bar and Chrome's massive URL bar taking up a huge portion of screen real estate, it makes mobile web apps using mobileui much less functional.

**Comment by fabiorogeriosj** [comment]
Yes, you need use this with cordova, see the doc: https://mobileui.github.io/#getting-started
