### ISSUE TITLE
Problem with UI after using OpenPage() and Swiper + Tab

### ISSUE THREAD

**Issue by momokaze** [MobileUI/components#147]
Hi, I got 2 problems.
1). After opening pages using OpenPage(), sometimes said page can keep scrolling down until index page shows up from behind. This issue always happens when Keyboard is on the screen
2). Using swiper, can swipe the whole page, making it blank.

re:
1) for this issues, I am using fadeOut with delay the whole index page after inside "body" tag while using OpenPage() , then creating custom backpage and onbackkeypress callback  that shows it again

**Comment by fabiorogeriosj** [comment]
I fix this!
