### ISSUE TITLE
Create the component toast

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#22]
## Component: toast
Inspiration in: https://ionicframework.com/docs/components/#toast

**Comment by braglin** [comment]
Hi,
I recently developed a plugin to work with Toast Messages in Wep applications, could you check it if you want!

I still need to do some changes.... mainly about positioning and borders...

[https://github.com/braglin/MyFakeToast](url)

**Comment by fabiorogeriosj** [comment]
@braglin it a good way!
For use in MobileUI I think that necessary add CSS, for simulater native UI, and add pure JS for open Toast.

Good Job.

**Comment by fabiorogeriosj** [comment]
Thanks @lucasssv <3
