### ISSUE TITLE
Create the component dialog

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#23]
## Component: dialog
Inspiration in: https://onsen.io/v2/docs/css.html#dialog-category

**Comment by FluffyKitty776** [comment]
```<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Dialog - Default functionality</title>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
window.alert = function(Message, title) {
if (title === undefined) {
 title = "This page says:";
}
    var myElementToShow = document.getElementById("dialog");
    myElementToShow.innerHTML = Message; 
    myElementToShow.setAttribute("title", title);
$( "#dialog" ).dialog();
}
});
  </script>
</head>
<body>
 
<div id="dialog" title=""></div>
<button onClick="window.alert('I am a alert box!');">click me!</button>
</body>
</html>
<!--All Of This Replaces The Default Dialog Box With The jquery Ui Dialog Hope This Helps With The Issue!-->

**Comment by fabiorogeriosj** [comment]
Hi @KitKat-Cat. To have an experience and design closer to the native I think it is better to create using CSS as the example of the issue! Thanks for the sugestion.

**Comment by KitKat-Cat** [comment]
@fabiorogeriosj Here is a example of a dialog element i made [https://github.com/KitKat-Cat/mobileui.github.io/blob/master/index.html](https://kitkat-cat.github.io/mobileui.github.io/)
and here is the source code for It that I forked from one of your projects [https://github.com/KitKat-Cat/mobileui.github.io/blob/master/index.html](https://github.com/KitKat-Cat/mobileui.github.io/blob/master/index.html) I hope this helps with this Issue.
