### ISSUE TITLE
Create the component progress-circular

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#32]
## Component: progress-circular
Inspiration in: http://www.cssscript.com/demo/pure-css-circular-percentage-bar/

**Comment by fabiorogeriosj** [comment]
CSS not good way, use js: https://jsfiddle.net/Aapn8/3410/

**Comment by fabiorogeriosj** [comment]
Another option: https://codepen.io/Kseso/pen/phiyL?editors=1100

**Comment by fabiorogeriosj** [comment]
https://codepen.io/MrThiagoBoni/pen/pJVVgd

**Comment by galloj** [comment]
@fabiorogeriosj I think this can be closed too
