### ISSUE TITLE
Create the component timeline

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#33]
## Component: timeline
See the images inspiration:
![image](https://cloud.githubusercontent.com/assets/1442874/25722044/18989b74-30e9-11e7-9daa-19fb6ee66dc7.png)

![image](https://cloud.githubusercontent.com/assets/1442874/25722062/28f0ff7a-30e9-11e7-9009-5465269836c6.png)

![image](https://cloud.githubusercontent.com/assets/1442874/25722170/850564cc-30e9-11e7-99ed-65c97000c1a4.png)

![image](https://cloud.githubusercontent.com/assets/1442874/25722180/897ae054-30e9-11e7-9a04-ea2f51f283d2.png)

**Comment by galloj** [comment]
@fabiorogeriosj This issue can be closed #39
