### ISSUE TITLE
Add support Chart.js

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#46]
## Component: chartjs
Using http://www.chartjs.org/samples/latest/

**Comment by Barathwaja** [comment]
Hi @fabiorogeriosj , you need to add a seperate component that uses chartjs so that ppl can easy plugin that into their app??

**Comment by fabiorogeriosj** [comment]
Hi @Barathwaja, i think if seperate is more simple for use in another components.
Today the `chartjs` is added in project components. Just need create a documentation and examples using it.

**Comment by fabiorogeriosj** [comment]
The idea is create a seperate componente using chartjs like this design:

https://play.google.com/store/apps/details?id=br.com.plugmobile.plugdash&hl=pt_BR

**Comment by Barathwaja** [comment]
You have added a chartbar component doc [https://mobileui.github.io/#chart-bar](https://mobileui.github.io/#chart-bar) on how to install and use like that for chartjs I need to do right? @fabiorogeriosj

**Comment by fabiorogeriosj** [comment]
this componente, chart-bar, not use chartjs, because it use pure CSS @Barathwaja

**Comment by Barathwaja** [comment]
@fabiorogeriosj Yes okay. Your asking me to create a documentation for chartjs component on how to install and use using MobileUI right?? Since you mentioned need to doc and add examples right in previous comment
