### ISSUE TITLE
Create componente calendar

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#55]
## Component: calendar
Inspiration:
![image](https://user-images.githubusercontent.com/1442874/27289868-cf2394c2-54e1-11e7-99b7-46ccd12ba301.png)
![image](https://user-images.githubusercontent.com/1442874/27289878-d89c8482-54e1-11e7-833f-e39381df7ea1.png)
![image](https://user-images.githubusercontent.com/1442874/27289896-e316fe9c-54e1-11e7-8093-63e1fb876378.png)
![image](https://user-images.githubusercontent.com/1442874/27289909-f2b079c8-54e1-11e7-9a8b-8b4e019c1f33.png)

**Comment by fabiorogeriosj** [comment]
https://codepen.io/RobVermeer/pen/zBgdwg

**Comment by hiteshpr** [comment]
I can work on this.
