### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Barathwaja** [MobileUI/components#57]
The MobileUI lacks documentation of how to begin for starters.

After adding **npm install -g mobileui** and **mobileui install header list** , while using preview getting this.
If this application is like a plugin, then mention that in documentation saying its a library or plugin, Install this this and that into your existing application and kick start.

I know my index.html is missing. What needs to be done be clear please.

Check the below error. I'm a beginner what to do ?? 

Also **mobileui --help** missing helping stuffs in terminal.

![image](https://user-images.githubusercontent.com/5066436/31084198-5fe2a288-a7b1-11e7-8db5-8b96daa2b726.png)

**Comment by fabiorogeriosj** [comment]
Hi @Barathwaja, you need enter in folder your project, example:

```
cordova create apptest
cd apptest
mobileui instal header list
mobileui preview
``` 

I agree that we need to improve the documentation for beginners.

**Comment by Barathwaja** [comment]
Yes it works. PR? and update docs along with Chart-js component doc?

**Comment by fabiorogeriosj** [comment]
Yes, good idea.

The docs about install and init in MobileUI is here: https://github.com/MobileUI/components/blob/master/base/install.html

**Comment by Barathwaja** [comment]
ok @fabiorogeriosj letme PR and work on this

**Comment by Barathwaja** [comment]
@fabiorogeriosj Check this PR [https://github.com/MobileUI/components/pull/58](https://github.com/MobileUI/components/pull/58)
