### ISSUE TITLE
Swiper not working on pages

### ISSUE THREAD

**Issue by fernrguez** [MobileUI/components#76]
Hi,

I'm a bit new on MobileUI and I think that is great, easy and to understand and learn. 
Following the sample code I was able to create a swiper on the index page that is working as expected but when I copied the code into a secondary page, it is displaying just the first element without the possibility to see the other elements nor display the pagination.

Is this behaviour expected or is there something missing on the example?

Thanks in advance

**Comment by fabiorogeriosj** [comment]
Hi @fernrguez , nice your feedback, thanks!

About swiper you need add a function after openPage for make a effects multiple pages, exemplo:


```HTML
<button onclick="goPageDemo()">Opne new page</button>
```

```JAVASCRIPT
function goPageDemo() {
    
    openPage('demo', function (){
        new Swiper('.swiper-container', {
            pagination: '.swiper-pagination',
            paginationClickable: true
        })     
    })

}
```

In this case, after page was open, the Swiper() will exec.
