### ISSUE TITLE
none of the jquery functions are working

### ISSUE THREAD

**Issue by himanshu244** [MobileUI/components#82]
the js not working in secont file file

![image](https://user-images.githubusercontent.com/40915125/42410794-b0b7924a-820d-11e8-82b9-0321b45d0cec.png)
![image](https://user-images.githubusercontent.com/40915125/42410795-b9ab4ae0-820d-11e8-9eae-0b6e7343fe05.png)

**Comment by fabiorogeriosj** [comment]
Hi, you can't use script in new page opned by openPage(), you need create a function and call after open page, example:

```
openPage('mypage.html', execFuncAfterLoad);

function execFuncAfterLoad(){
  alert('hello');
}
```

In your new HTML file (mypage.html) you can put just HTML tags and CSS.

**Comment by himanshu244** [comment]
in your code which page is this mypage.html is this the second page name

**Comment by fabiorogeriosj** [comment]
the function `execFuncAfterLoad` is in index.js

**Comment by himanshu244** [comment]
openPage('mypage.html', execFuncAfterLoad);

in this function "mypage.html"   is what???

**Comment by fabiorogeriosj** [comment]
name of html file, in your example (looking at your screens) you need put `openPage('t2', funcNameCreatedInIndex)`, and create a function `funcNameCreatedInIndex` in your index.js file (/js/index.js).

**Comment by himanshu244** [comment]
can i create **funcNameCreateInIndex** function in t2.html.

**Comment by himanshu244** [comment]
can you please share full demo example with me
which includes atleast two functions executed

**Comment by himanshu244** [comment]
sir its not working please help I am new to this
please share full example demo containing more than two functions

**Comment by fabiorogeriosj** [comment]
No, you can't! All your funcs you need create in file loaded in your index.html, example index.js!
Because t2.html is open by Ajax (openPage()) and not load script into page.

A create example for you here: https://github.com/MobileUI/demos/tree/master/page

**Comment by himanshu244** [comment]
okay thanks a lot sir :-)
