### ISSUE TITLE
link to full library (css and js)

### ISSUE THREAD

**Issue by BilalBoulifa** [MobileUI/components#88]
I would like to include this in a web page, where can I find the css and js files ?

**Comment by BilalBoulifa** [comment]
any update on this guys, this should be straightforward its just the complete css and js in one file, minified if possible should be nice, otherwise I will minify it.

**Comment by fabiorogeriosj** [comment]
Hi @fithwith, these components were created for mobile apps, I don't know if is ok in web page.
But you can use the components installed in app, example:

$mobileui install header list button cover nameOfOtherComponet

Just copy the folder into www/mobileui

**Comment by BilalBoulifa** [comment]
actually its a web page but it will open in mobile, my only issue that I wanted to important all the components at once, one css file and one js file, till now I was doing it manually one by one adding the css and js in this repo and its really tedious, specially sometimes its not straightforward, one day I was struggling with the header finally I discovered that you need to add the files /base/reset.css.

anyway I will try to generate it like you said, but having a link available with the library in one file minified this will be really a nice thing, this will help people use the library wherever they want not only (Cordova, PhoneGap, Ionic Framework, Onsen UI, Framework7), it will work even for customized stuff.

the library is really nice light and efficient, I'm seeing right now it has not too many stars but I'm pretty sure its coming, so keep going the good job.
