### ISSUE TITLE
Create input type Range

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#9]
## Component: input
Inspiration in: https://ionicframework.com/docs/components/#range

**Comment by iamgbayer** [comment]
I think I can contribute with this component :grimacing:

**Comment by fabiorogeriosj** [comment]
Nice @guuibayer, your contribution is welcome ;)

Here is another inspiratoin: https://onsen.io/v2/docs/css.html#range-category

I think it's good if component need little HTML, example:
```HTML
<input type="range" class="blue">
```
With icons:
```HTML
<div class="left">
  <i class="icon ion-icon1"></i>
</div>
<input type="range" class="blue">
<div class="right">
  <i class="icon ion-icon2"></i>
</div>
```
