### ISSUE TITLE
Create the align-bottom in base component

### ISSUE THREAD

**Issue by fabiorogeriosj** [MobileUI/components#91]
work in `.list .align-bottom` equal align-top

**Comment by phoenix1796** [comment]
I'd like to work on this!

**Comment by fabiorogeriosj** [comment]
Nice @phoenix1796, you can see this example: 
```
.list .align-top {
  -ms-flex-align: center;
  -webkit-align-items: center;
  align-items: baseline;
  margin-top: 10px;
}
```

In here: https://github.com/MobileUI/components/blob/master/list/style.css
